# Generated by Django 4.2.1 on 2023-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='studentmarks',
            field=models.ManyToManyField(related_name='stu_marks', to='Student.marks'),
        ),
    ]
