# Generated by Django 4.2.1 on 2023-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_marks_student_student_studentmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentmarks',
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ManyToManyField(related_name='studentmarks', to='Student.student'),
        ),
    ]
